# Generated by Django 4.2.4 on 2023-09-06 20:42

from django.db import migrations, models
import todo_app.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_update_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('1', 'todo'), ('2', 'in progress'), ('3', 'done')], default='1', max_length=1)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ToDo',
                'verbose_name_plural': 'ToDos',
                'ordering': ('-last_update_datetime',),
                'abstract': False,
            },
            bases=(models.Model, todo_app.models.TodoStatusTranslatorMixin, todo_app.models.DateTimeTranslatorMixin),
        ),
    ]
