# Generated by Django 4.2.4 on 2023-09-19 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('login_datetime', models.DateTimeField(auto_now_add=True)),
                ('logout_datetime', models.DateTimeField(blank=True, null=True)),
                ('is_valid', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
